"""Proof that the Codex-home guard fails a leaking test, end to end.

``tests/unit/test_codex_home_isolation.py`` covers the rule and this session's
own environment. What it cannot show is that the guard is actually wired into
every test - that a *newly added* codex-spawning test which points
``CODEX_HOME`` back at the operator's home fails instead of quietly leaking.

So this runs pytest in a subprocess over generated tests, loading the very same
``tests.codex_home`` plugin the whole suite loads, and asserts on the verdicts:
each leaking spawn fails with the guard's message, the isolated one passes.
A fake executable named ``codex`` means nothing here talks to the real CLI -
the guard raises before the leaking spawns start, and the control case starts
the stand-in.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

from tests.codex_home import CODEX_HOME_ENV, CODEX_HOME_POLICY
from tests.integration.conftest import xdist_timeout

_REPO_ROOT = Path(__file__).resolve().parents[2]

# Three ways a codex spawn can reach the operator's home - inherited process
# env, an explicitly built subprocess env, and a PTY spawn - plus one isolated
# control so the guard is shown to block leaks rather than everything.
_GENERATED_TESTS = '''\
"""Generated by tests/integration/test_codex_home_isolation.py."""

import os
import subprocess

import pexpect

FAKE_CODEX = os.environ["FAKE_CODEX_BINARY"]
OPERATOR_HOME = os.environ["OPERATOR_CODEX_HOME"]


def test_leaks_via_process_environment(monkeypatch):
    monkeypatch.setenv("CODEX_HOME", OPERATOR_HOME)
    subprocess.run([FAKE_CODEX, "exec", "hello"], capture_output=True)


def test_leaks_via_subprocess_env_without_codex_home():
    subprocess.run([FAKE_CODEX, "exec", "hello"], capture_output=True, env={})


def test_leaks_via_pexpect_spawn():
    pexpect.spawn(
        "/bin/bash",
        ["-c", FAKE_CODEX + " exec hello"],
        env={"CODEX_HOME": os.path.join(OPERATOR_HOME, "sessions")},
    )


def test_isolated_spawn_is_allowed():
    result = subprocess.run([FAKE_CODEX, "exec", "hello"], capture_output=True)
    assert result.returncode == 0
'''


@pytest.fixture(scope="module")
def guard_verdicts(
    tmp_path_factory: pytest.TempPathFactory,
) -> subprocess.CompletedProcess[str]:
    """Run the generated suite once and share its verdicts with every test."""
    workdir = tmp_path_factory.mktemp("codex-home-guard")
    fake_codex = workdir / "bin" / "codex"
    fake_codex.parent.mkdir(parents=True)
    fake_codex.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    fake_codex.chmod(0o755)

    test_file = workdir / "test_generated_codex_home_leaks.py"
    test_file.write_text(_GENERATED_TESTS, encoding="utf-8")

    return subprocess.run(
        [
            sys.executable,
            "-m",
            "pytest",
            str(test_file),
            "-p",
            "tests.codex_home",
            "-p",
            "no:cacheprovider",
            "-q",
            "--no-header",
            "--tb=line",
        ],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        timeout=xdist_timeout(180.0),
        env=_nested_environment(fake_codex),
    )


def _nested_environment(fake_codex: Path) -> dict[str, str]:
    """Environment for the nested run.

    ``CODEX_HOME`` is pinned to this session's operator home so the nested
    process resolves the same home to protect, and ``PYTHONPATH`` makes the
    ``tests`` package importable as a plugin.
    """
    env = dict(os.environ)
    env[CODEX_HOME_ENV] = str(CODEX_HOME_POLICY.operator_home)
    env["FAKE_CODEX_BINARY"] = str(fake_codex)
    env["OPERATOR_CODEX_HOME"] = str(CODEX_HOME_POLICY.operator_home)
    pythonpath = [str(_REPO_ROOT), str(_REPO_ROOT / "src")]
    if env.get("PYTHONPATH"):
        pythonpath.append(env["PYTHONPATH"])
    env["PYTHONPATH"] = ":".join(pythonpath)
    return env


def _report(result: subprocess.CompletedProcess[str]) -> str:
    return f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"


@pytest.mark.integration
def test_every_leaking_codex_spawn_fails_its_test(
    guard_verdicts: subprocess.CompletedProcess[str],
) -> None:
    report = _report(guard_verdicts)
    assert guard_verdicts.returncode != 0, f"a leaking codex spawn was allowed\n{report}"
    assert "3 failed" in guard_verdicts.stdout, report
    assert guard_verdicts.stdout.count("Codex home leak") >= 3, report


@pytest.mark.integration
def test_isolated_codex_spawn_still_runs(
    guard_verdicts: subprocess.CompletedProcess[str],
) -> None:
    """The guard blocks leaks, not Codex itself - live tests must still spawn."""
    assert "1 passed" in guard_verdicts.stdout, _report(guard_verdicts)


@pytest.mark.integration
def test_guard_names_the_operator_home_and_both_leak_shapes(
    guard_verdicts: subprocess.CompletedProcess[str],
) -> None:
    report = _report(guard_verdicts)
    assert str(CODEX_HOME_POLICY.operator_home) in guard_verdicts.stdout, report
    assert f"{CODEX_HOME_ENV} is unset" in guard_verdicts.stdout, report
    assert "resolves inside the operator's Codex home" in guard_verdicts.stdout, report
